NationalGenomicsInfrastructure/standalone_scripts

README.md
couchdb_replication.py

updated it to take yaml config files and encrypted password

added replication script from scilifelab, 

---

couchdb_replication.py

trying to fix the 2-arg call

---

update_bioinfo_deliveries.py

This script creates a new sheet here:
https://docs.google.com/spreadsheets/d/1e_vYSd0ox07ztgFu5JdnkKFS8rB9nwtRARN9iPj87bg/edit#gid=84929094
with updated info on what projects are currently under delivery by production.
For now kept as a private script run only by me...

update bioinfo spreadsheet

---

repooler.py

Fixed some minor runtime errors that popped up when repooling a previously repooled project.
Also cleaned up outdated comments, and some false numpy error messages.

Repooler runtime fixes

---

backup_github.py

Resolves #6 .
Requires a password now though.

Backup script now copies private repos. Requires password though

---

repooler.py

Added a dumpfile so results can be more easily traced. Will probably update this a fair bit.
Also solved an issue that caused an incorrect amount of lanes to be suggested.

Repooler update

---

README.md
zendesk_attachment_backup.py

tools only runs py 2.6 by default. Changed shebang and added instructions for installed conda with py2.7.

Changed zendesk shebang to use env perl

---

README.md
set_bioinforesponsible.py

Notably faster for setting bioinfo responsible when LIMS web interface is being a bit slow.
Core functionality could probably be ported to genomics-stage. Solution is so lightweight it is worth having on its own though.

Added set_bioinforesponsible script

---

zendesk_attachment_backup.py

one hard fix and a couple of rewrites.

fixing what @isbm found

---

fix_double_flowcell.py

adding double flowcell fix

---

project_status.py

Version 1, written by Francesco. Checking status of given project and all its samples. Updates are coming.

Project Status Script

---

backup_github.py

- Refactored logging to suppress github stdout output
- Backup is now compressed and moved
- Removed implicit ruby dependency
- Improved logging & made exceptions more explicit

Updated backup_github a lot

---

get_sample_names.py

Script from Senthil, deployed on milou

get_sample_names.py: list of analyzed samples with user id

---

project_status_extended.py

Extended version of project status script. 
(It was decided to keep both versions, as the previous one handles Uppsala projects as well, but this one has more options only applicable for Stockholm projects.)

Project Status

---

README.md
use_undetermined.sh

create softlinks for undetermined, to be used in the analysis

use_undetermined.sh

---

README.md
compute_production_stats.py
runs_per_week.sh

Some useful scripts that I use to keep an eye on production trends.

few practical stand alone script

---

snic_util.py

`metavar=""` breaks the code while looking for help message. Removing it work fine 👍

Remove metavar

---

snic_util.py

Added the --update-databases flag on command line to enable saving the generated GRUS delivery project back to Charon and statusdb.

Added option to save created delivery project to be saved back to Charon and statusdb

---

Gdrivebackup.sh

The script is to be run on ngi.transfer

Script to backup Google Drive directories to homer

---

push_new_pricing_to_statusdb.py
update_exchange_rates.py

- Minor adjustment of keynames in the exchange rate script.
- Changed an exception to a warning for discontinued components used within products.

Slightly smaller updates to the pricing scripts

---

sample_information_validator.py

(1) now summarising warning messages instead of single warnings. (2) does not check the project name, prints it instead. (3) fixed issues with numeric check. (4) can handle now Methods that do not have requirements.

Fixes upon request of project coordinators

---

Gdrivebackup.sh

cron has issues running the script unless the password is passed explicitly.

Updates to make cron run mount

---

del_bupp_files.py

Updates include:
- Will delete more files to save disk space
- Commented the logic behind the dates a bit more thorough
- Slightly more fault tolerant for files which are not backups

Updated del_bupp_files to delete more backups

---

Gdrivebackup.sh

The old way didn't seem to work.

Fix bug in GDrive Backup

---

print_label.py

* Moved [constructBasicProjectBarcodeLabels.py](https://github.com/SciLifeLab/scilifelab/blob/master/scripts/constructBasicProjectBarcodeLabels.py) script to this repo from the now-archived [SciLifeLab/scilifelab](https://github.com/SciLifeLab/scilifelab/) repository.
* Renamed to a slightly more type-able `print_label.py`
* Rewrote code to work with Python 3, switch out depreciated libraries and drop old-fashioned python behaviour
> _This is kind of cathartic, in the same way that it's really satisfying to unblock a really disgusting drain or something_
Original changes to be able to modify the number of plates introduced by @ormestad

New, updated script to print plate barcodes

---

statusdb_snicuser_checker.py

This script can run only on ngi-internal (or irma) as the SNIC API is IP restricted.

Add script to check SNIC user status on ngi-internal

---

update_exchange_rates.py

Adopting to the new conf file, removing the yaml load warning and fixing a typo.

Slight updates of the update_exchange_rates script

---

sensorpush_to_statusdb.py

Turned out I needed to change the script quite a lot. It is now designed to run hourly and to fetch each sensor individually, this generates more requests, but minimises the payload size from the API which is apparently the cause of the timeout issues I had.
The database document is still per 24 hours so the script can now handle a merge of the newly fetched data and the existing data in the database.

Sensorpush api refactor

---

Gdrivebackup.sh
statusdb_snicuser_checker.py

The Gdrive sync script is a bit useless after their tool update.

Updates to scripts

---

check_dirty.py

Added repo name and untracked files to output.

updated to add repo names

---

check_dirty.py

updated to take multiple repos as input and check all of them in a loop.

updated to handle multiple repos
